# Generated by Django 5.1.7 on 2025-05-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrinho_categoria_itemcarrinho_itempedido_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='aplicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peca',
            name='codigos_alternativos',
            field=models.CharField(blank=True, help_text='Códigos alternativos separados por vírgula', max_length=500, null=True),
        ),
    ]
