# Generated by Django 5.1.7 on 2025-05-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_peca_aplicacao_peca_codigos_alternativos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='estoque',
        ),
    ]
