# Generated by Django 5.1.7 on 2025-06-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_peca_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefone',
        ),
    ]
