# Generated by Django 5.2.3 on 2025-06-14 01:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_pedido_email_remove_pedido_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
